// Generated by CIRCT 472531b63
module add(	// test-add-no-pack/add-no-pack-sv-prettified-sv.mlir:2:3
  input  [31:0] a,	// test-add-no-pack/add-no-pack-sv-prettified-sv.mlir:2:21
  input         a_valid,	// test-add-no-pack/add-no-pack-sv-prettified-sv.mlir:2:34
  output        a_ready,	// test-add-no-pack/add-no-pack-sv-prettified-sv.mlir:2:53
  output [31:0] out0	// test-add-no-pack/add-no-pack-sv-prettified-sv.mlir:2:71
);

  assign a_ready = 1'h1;	// test-add-no-pack/add-no-pack-sv-prettified-sv.mlir:4:13, :7:5
  assign out0 = {a[30:0], 1'h0};	// test-add-no-pack/add-no-pack-sv-prettified-sv.mlir:3:14, :5:10, :6:10, :7:5
endmodule


