; solver scope 0
(assert (let ((tmp (exists ((tmp_0 Int) (tmp_1 Int))
( ! (let ((tmp_2 (= tmp_1 4)))
                           (let ((tmp_3 (= tmp_0 3)))
                           (let ((tmp_4 (= tmp_3 tmp_2)))
                           tmp_4)))
                            :pattern ((let ((tmp_5 (= tmp_0 3)))
                           tmp_5)(let ((tmp_6 (= tmp_1 4)))
                           tmp_6))))))
        tmp))
(check-sat)
(reset)
