// Generated by CIRCT unknown git version
module mux(	// select/select-sv-prettified-sv.mlir:2:3
  input         select,	// select/select-sv-prettified-sv.mlir:2:21
                select_valid,	// select/select-sv-prettified-sv.mlir:2:38
  input  [63:0] a,	// select/select-sv-prettified-sv.mlir:2:61
  input         a_valid,	// select/select-sv-prettified-sv.mlir:2:74
  input  [63:0] b,	// select/select-sv-prettified-sv.mlir:2:92
  input         b_valid,	// select/select-sv-prettified-sv.mlir:2:105
                clk,	// select/select-sv-prettified-sv.mlir:2:123
                rst,	// select/select-sv-prettified-sv.mlir:2:137
                out0_ready,	// select/select-sv-prettified-sv.mlir:2:151
  output        select_ready,	// select/select-sv-prettified-sv.mlir:2:173
                a_ready,	// select/select-sv-prettified-sv.mlir:2:196
                b_ready,	// select/select-sv-prettified-sv.mlir:2:214
  output [63:0] out0,	// select/select-sv-prettified-sv.mlir:2:232
  output        out0_valid	// select/select-sv-prettified-sv.mlir:2:248
);

  wire       _GEN = select == 1'h0;	// select/select-sv-prettified-sv.mlir:3:14, :4:10
  wire [1:0] _GEN_0 = 2'h1 << _GEN;	// select/select-sv-prettified-sv.mlir:4:10, :8:14, :9:10
  wire       _GEN_1 = (_GEN ? a_valid : b_valid) & select_valid;	// select/select-sv-prettified-sv.mlir:4:10, :10:10, :11:10
  wire       _GEN_2 = _GEN_1 & out0_ready;	// select/select-sv-prettified-sv.mlir:11:10, :12:10
  assign select_ready = _GEN_2;	// select/select-sv-prettified-sv.mlir:12:10, :17:5
  assign a_ready = _GEN_0[1] & _GEN_2;	// select/select-sv-prettified-sv.mlir:9:10, :12:10, :15:10, :16:11, :17:5
  assign b_ready = _GEN_0[0] & _GEN_2;	// select/select-sv-prettified-sv.mlir:9:10, :12:10, :13:10, :14:10, :17:5
  assign out0 = _GEN ? b : a;	// select/select-sv-prettified-sv.mlir:4:10, :5:10, :17:5
  assign out0_valid = _GEN_1;	// select/select-sv-prettified-sv.mlir:11:10, :17:5
endmodule

module {
  hw.module @mux(in %select : i1, in %select_valid : i1, in %a : i64, in %a_valid : i1, in %b : i64, in %b_valid : i1, in %clk : i1, in %rst : i1, in %out0_ready : i1, out select_ready : i1, out a_ready : i1, out b_ready : i1, out out0 : i64, out out0_valid : i1) {
    %false = hw.constant false
    %0 = comb.icmp eq %select, %false : i1
    %1 = sv.wire {hw.verilogName = "_GEN"} : !hw.inout<i1>
    sv.assign %1, %0 : i1
    %2 = sv.read_inout %1 : !hw.inout<i1>
    %3 = comb.mux %2, %b, %a : i64
    %false_0 = hw.constant false
    %4 = sv.read_inout %1 : !hw.inout<i1>
    %5 = comb.concat %false_0, %4 : i1, i1
    %c1_i2 = hw.constant 1 : i2
    %6 = comb.shl %c1_i2, %5 : i2
    %7 = sv.wire {hw.verilogName = "_GEN_0"} : !hw.inout<i2>
    sv.assign %7, %6 : i2
    %8 = sv.read_inout %1 : !hw.inout<i1>
    %9 = comb.mux %8, %a_valid, %b_valid : i1
    %10 = comb.and %9, %select_valid : i1
    %11 = sv.wire {hw.verilogName = "_GEN_1"} : !hw.inout<i1>
    sv.assign %11, %10 : i1
    %12 = sv.read_inout %11 : !hw.inout<i1>
    %13 = comb.and %12, %out0_ready : i1
    %14 = sv.wire {hw.verilogName = "_GEN_2"} : !hw.inout<i1>
    sv.assign %14, %13 : i1
    %15 = sv.read_inout %7 : !hw.inout<i2>
    %16 = comb.extract %15 from 0 : (i2) -> i1
    %17 = sv.read_inout %14 : !hw.inout<i1>
    %18 = comb.and %16, %17 : i1
    %19 = sv.read_inout %7 : !hw.inout<i2>
    %20 = comb.extract %19 from 1 : (i2) -> i1
    %21 = sv.read_inout %14 : !hw.inout<i1>
    %22 = comb.and %20, %21 : i1
    %23 = sv.read_inout %11 : !hw.inout<i1>
    %24 = sv.read_inout %14 : !hw.inout<i1>
    hw.output %24, %22, %18, %3, %23 : i1, i1, i1, i64, i1
  }
}

