// Generated by CIRCT unknown git version
module mux(	// select/select-sv-prettified-sv.mlir:2:3
  input         select,	// select/select-sv-prettified-sv.mlir:2:21
                select_valid,	// select/select-sv-prettified-sv.mlir:2:38
  input  [63:0] a,	// select/select-sv-prettified-sv.mlir:2:61
  input         a_valid,	// select/select-sv-prettified-sv.mlir:2:74
  input  [63:0] b,	// select/select-sv-prettified-sv.mlir:2:92
  input         b_valid,	// select/select-sv-prettified-sv.mlir:2:105
                clk,	// select/select-sv-prettified-sv.mlir:2:123
                rst,	// select/select-sv-prettified-sv.mlir:2:137
                out0_ready,	// select/select-sv-prettified-sv.mlir:2:151
  output        select_ready,	// select/select-sv-prettified-sv.mlir:2:173
                a_ready,	// select/select-sv-prettified-sv.mlir:2:196
                b_ready,	// select/select-sv-prettified-sv.mlir:2:214
  output [63:0] out0,	// select/select-sv-prettified-sv.mlir:2:232
  output        out0_valid	// select/select-sv-prettified-sv.mlir:2:248
);

  wire       _GEN = select == 1'h0;	// select/select-sv-prettified-sv.mlir:3:14, :4:10
  wire [1:0] _GEN_0 = 2'h1 << _GEN;	// select/select-sv-prettified-sv.mlir:4:10, :8:14, :9:10
  wire       _GEN_1 = (_GEN ? a_valid : b_valid) & select_valid;	// select/select-sv-prettified-sv.mlir:4:10, :10:10, :11:10
  wire       _GEN_2 = _GEN_1 & out0_ready;	// select/select-sv-prettified-sv.mlir:11:10, :12:10
  assign select_ready = _GEN_2;	// select/select-sv-prettified-sv.mlir:12:10, :17:5
  assign a_ready = _GEN_0[1] & _GEN_2;	// select/select-sv-prettified-sv.mlir:9:10, :12:10, :15:10, :16:11, :17:5
  assign b_ready = _GEN_0[0] & _GEN_2;	// select/select-sv-prettified-sv.mlir:9:10, :12:10, :13:10, :14:10, :17:5
  assign out0 = _GEN ? b : a;	// select/select-sv-prettified-sv.mlir:4:10, :5:10, :17:5
  assign out0_valid = _GEN_1;	// select/select-sv-prettified-sv.mlir:11:10, :17:5
endmodule