// Generated by CIRCT 472531b63
module test_control_merge(	// test-unpack-token/unpack-sv-prettified-sv.mlir:2:3
     input  [63:0]         _GEN,	// test-unpack-token/unpack-sv-prettified-sv.mlir:2:36
     input                 _valid,	// test-unpack-token/unpack-sv-prettified-sv.mlir:2:52
                           out0_ready,	// test-unpack-token/unpack-sv-prettified-sv.mlir:2:69
     output                _ready,	// test-unpack-token/unpack-sv-prettified-sv.mlir:2:91
  // output /*Zero Width*/ out0,	// test-unpack-token/unpack-sv-prettified-sv.mlir:2:108
     output                out0_valid	// test-unpack-token/unpack-sv-prettified-sv.mlir:2:123
);

  assign _ready = out0_ready;	// test-unpack-token/unpack-sv-prettified-sv.mlir:4:5
  // Zero width: assign out0 = /*Zero width*/;	// test-unpack-token/unpack-sv-prettified-sv.mlir:4:5
  assign out0_valid = _valid;	// test-unpack-token/unpack-sv-prettified-sv.mlir:4:5
endmodule
