// Generated by CIRCT 472531b63
module test_control_merge(	// test-unpack-value/unpack-sv-prettified-sv.mlir:2:3
  input  [63:0] _GEN,	// test-unpack-value/unpack-sv-prettified-sv.mlir:2:36
  input         _valid,	// test-unpack-value/unpack-sv-prettified-sv.mlir:2:52
  output        _ready,	// test-unpack-value/unpack-sv-prettified-sv.mlir:2:70
  output [63:0] out0	// test-unpack-value/unpack-sv-prettified-sv.mlir:2:87
);

  assign _ready = 1'h1;	// test-unpack-value/unpack-sv-prettified-sv.mlir:3:13, :4:5
  assign out0 = _GEN;	// test-unpack-value/unpack-sv-prettified-sv.mlir:4:5
endmodule

