// Generated by CIRCT unknown git version
module test_conditional_branch(	// test-branch/branch-sv-prettified-sv.mlir:2:3
     input                           arg0,	// test-branch/branch-sv-prettified-sv.mlir:2:41
                                     arg0_valid,	// test-branch/branch-sv-prettified-sv.mlir:2:56
     input  <<invalid type 'index'>> arg1,	// test-branch/branch-sv-prettified-sv.mlir:2:77
     input                           arg1_valid,	// test-branch/branch-sv-prettified-sv.mlir:2:95
  // input  /*Zero Width*/           arg2,	// test-branch/branch-sv-prettified-sv.mlir:2:116
     input                           arg2_valid,	// test-branch/branch-sv-prettified-sv.mlir:2:131
                                     clk,	// test-branch/branch-sv-prettified-sv.mlir:2:152
                                     rst,	// test-branch/branch-sv-prettified-sv.mlir:2:166
                                     out0_ready,	// test-branch/branch-sv-prettified-sv.mlir:2:180
                                     out1_ready,	// test-branch/branch-sv-prettified-sv.mlir:2:201
                                     out2_ready,	// test-branch/branch-sv-prettified-sv.mlir:2:222
     output                          arg0_ready,	// test-branch/branch-sv-prettified-sv.mlir:2:244
                                     arg1_ready,	// test-branch/branch-sv-prettified-sv.mlir:2:265
                                     arg2_ready,	// test-branch/branch-sv-prettified-sv.mlir:2:286
     output <<invalid type 'index'>> out0,	// test-branch/branch-sv-prettified-sv.mlir:2:307
     output                          out0_valid,	// test-branch/branch-sv-prettified-sv.mlir:2:325
     output <<invalid type 'index'>> out1,	// test-branch/branch-sv-prettified-sv.mlir:2:346
     output                          out1_valid,	// test-branch/branch-sv-prettified-sv.mlir:2:364
  // output /*Zero Width*/           out2,	// test-branch/branch-sv-prettified-sv.mlir:2:385
     output                          out2_valid	// test-branch/branch-sv-prettified-sv.mlir:2:400
);

  wire _GEN;	// test-branch/branch-sv-prettified-sv.mlir:10:10
  wire _GEN_0 = arg0_valid & arg1_valid;	// test-branch/branch-sv-prettified-sv.mlir:3:10
  wire _GEN_1 = _GEN & _GEN_0;	// test-branch/branch-sv-prettified-sv.mlir:3:10, :4:10, :10:10
  assign _GEN = (arg0 ? out0_ready : out1_ready) & _GEN_0;	// test-branch/branch-sv-prettified-sv.mlir:3:10, :9:10, :10:10
  assign arg0_ready = _GEN_1;	// test-branch/branch-sv-prettified-sv.mlir:4:10, :11:5
  assign arg1_ready = _GEN_1;	// test-branch/branch-sv-prettified-sv.mlir:4:10, :11:5
  assign arg2_ready = out2_ready;	// test-branch/branch-sv-prettified-sv.mlir:11:5
  assign out0 = arg1;	// test-branch/branch-sv-prettified-sv.mlir:11:5
  assign out0_valid = arg0 & _GEN_0;	// test-branch/branch-sv-prettified-sv.mlir:3:10, :5:10, :11:5
  assign out1 = arg1;	// test-branch/branch-sv-prettified-sv.mlir:11:5
  assign out1_valid = ~arg0 & _GEN_0;	// test-branch/branch-sv-prettified-sv.mlir:3:10, :7:10, :8:10, :11:5
  // Zero width: assign out2 = arg2;	// test-branch/branch-sv-prettified-sv.mlir:11:5
  assign out2_valid = arg2_valid;	// test-branch/branch-sv-prettified-sv.mlir:11:5
endmodule

module {
  hw.module @test_conditional_branch(in %arg0 : i1, in %arg0_valid : i1, in %arg1 : index, in %arg1_valid : i1, in %arg2 : i0, in %arg2_valid : i1, in %clk : i1, in %rst : i1, in %out0_ready : i1, in %out1_ready : i1, in %out2_ready : i1, out arg0_ready : i1, out arg1_ready : i1, out arg2_ready : i1, out out0 : index, out out0_valid : i1, out out1 : index, out out1_valid : i1, out out2 : i0, out out2_valid : i1) {
    %0 = sv.wire {hw.verilogName = "_GEN"} : !hw.inout<i1>
    %1 = comb.and %arg0_valid, %arg1_valid : i1
    %2 = sv.wire {hw.verilogName = "_GEN_0"} : !hw.inout<i1>
    sv.assign %2, %1 : i1
    %3 = sv.read_inout %2 : !hw.inout<i1>
    %4 = sv.read_inout %0 : !hw.inout<i1>
    %5 = comb.and %4, %3 : i1
    %6 = sv.wire {hw.verilogName = "_GEN_1"} : !hw.inout<i1>
    sv.assign %6, %5 : i1
    %7 = sv.read_inout %2 : !hw.inout<i1>
    %8 = comb.and %arg0, %7 : i1
    %true = hw.constant true
    %9 = comb.xor %arg0, %true : i1
    %10 = sv.read_inout %2 : !hw.inout<i1>
    %11 = comb.and %9, %10 : i1
    %12 = comb.mux %arg0, %out0_ready, %out1_ready : i1
    %13 = sv.read_inout %2 : !hw.inout<i1>
    %14 = comb.and %12, %13 : i1
    sv.assign %0, %14 : i1
    %15 = sv.read_inout %6 : !hw.inout<i1>
    %16 = sv.read_inout %6 : !hw.inout<i1>
    hw.output %16, %15, %out2_ready, %arg1, %8, %arg1, %11, %arg2, %arg2_valid : i1, i1, i1, index, i1, index, i1, i0, i1
  }
}

