// Generated by CIRCT 472531b63
module test_control_merge(	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:3
  // input  /*Zero Width*/ arg0,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:36
     input                 arg0_valid,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:51
  // input  /*Zero Width*/ arg1,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:72
     input                 arg1_valid,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:87
                           clk,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:108
                           rst,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:122
                           out0_ready,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:136
                           out1_ready,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:157
     output                arg0_ready,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:179
                           arg1_ready,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:200
  // output /*Zero Width*/ out0,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:221
     output                out0_valid,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:236
                           out1,	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:257
                           out1_valid	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:2:272
);

  wire allDone;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:38:11
  wire done1;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:37:11
  wire done0;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:24:11
  wire _GEN = arg0_valid | arg1_valid;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:3:10
  wire _GEN_0 = _GEN & allDone;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:3:10, :5:10, :38:11
  reg  emitted_0;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:14:18
  always_ff @(posedge clk) begin	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:16:5
    if (rst)	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:16:5
      emitted_0 <= 1'h0;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:10:14, :19:7
    else	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:16:5
      emitted_0 <= done0 & ~allDone;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:12:10, :13:10, :17:7, :24:11, :38:11
  end // always_ff @(posedge)
  wire _GEN_1 = ~emitted_0 & _GEN;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:3:10, :15:10, :21:10, :22:10
  assign done0 = out1_ready & _GEN_1 | emitted_0;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:15:10, :22:10, :23:11, :24:11
  reg  emitted_1;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:27:18
  always_ff @(posedge clk) begin	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:29:5
    if (rst)	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:29:5
      emitted_1 <= 1'h0;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:10:14, :32:7
    else	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:29:5
      emitted_1 <= done1 & ~allDone;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:25:11, :26:11, :30:7, :37:11, :38:11
  end // always_ff @(posedge)
  wire _GEN_2 = ~emitted_1 & _GEN;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:3:10, :28:11, :34:11, :35:11
  assign done1 = out0_ready & _GEN_2 | emitted_1;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:28:11, :35:11, :36:11, :37:11
  assign allDone = done0 & done1;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:24:11, :37:11, :38:11
  assign arg0_ready = _GEN_0 & arg0_valid;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:5:10, :6:10, :40:5
  assign arg1_ready = _GEN_0 & ~arg0_valid;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:5:10, :7:10, :8:10, :40:5
  // Zero width: assign out0 = /*Zero width*/;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:40:5
  assign out0_valid = _GEN_2;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:35:11, :40:5
  assign out1 = ~arg0_valid;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:39:11, :40:5
  assign out1_valid = _GEN_1;	// test-merge-replace-idx-with-i64/merge-sv-prettified-sv.mlir:22:10, :40:5
endmodule
