#include "Vunpack__02dexport.h" // The name of the header generated by Verilator
#include "verilated.h"

int main(int argc, char** argv) {
    // Create Verilated context
    Verilated::commandArgs(argc, argv);

    // Instantiate your module (replace V_TOP_MODULE with your top module name)
    Vunpack__02dexport* top = new Vunpack__02dexport;

    // Simple simulation loop
    while (!Verilated::gotFinish()) {
        top->eval();
    }

    // Cleanup
    delete top;
    return 0;
}
