// Generated by CIRCT 472531b63
module add(	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:3
  input  [31:0] a,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:21
  input         a_valid,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:34
  input  [31:0] b,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:52
  input         b_valid,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:65
                clk,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:83
                rst,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:97
                out0_ready,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:111
  output        a_ready,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:133
                b_ready,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:151
  output [31:0] out0,	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:169
  output        out0_valid	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:2:185
);

  assign a_ready = out0_ready;	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:7:5
  assign b_ready = 1'h1;	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:3:13, :7:5
  assign out0 = {a[30:0], 1'h0};	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:4:14, :5:10, :6:10, :7:5
  assign out0_valid = a_valid;	// test-add-with-pack/add-with-pack-sv-prettified-sv.mlir:7:5
endmodule


